version: '3'

services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:3001
    restart: unless-stopped
    networks:
      - flippo-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - flippo-network

networks:
  flippo-network:
    driver: bridge 